// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "../include/main.h"

extern const struct gpio_dt_spec led = GPIO_DT_SPEC_GET(LED0_NODE, gpios);

void On_LED_func(lv_event_t * e)
{
	gpio_pin_set_dt(&led, true);
}

void Off_LED_func(lv_event_t * e)
{
		gpio_pin_set_dt(&led, false);

}
